### ISSUE TITLE
Should initial submission respond w/token?

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/stately#14]
Picture this scenario: a user initiates a travel request. It `POST`s to `/api/travel-request/`, which responds `200` along with the newly created case object:

``` json
{
    "workflow": {
        "id": 3,
        "name": "Travel Request",
        "slug": "travel-request"
    },
    "state": {
        "name": "Awaiting Supervisor Approval",
        "actions": []
    },
    "id": 6,
    "events": [{
        "actor": null,
        "timestamp": "2016-09-29T11:55:01.806Z",
        "data": {
            "cost": "120",
            "name": "John Doe",
            "destination": "Harrisburg",
            "supervisor_email": "tim@timwis.com"
        }
    }],
    "data": {
        "cost": "120",
        "name": "John Doe",
        "destination": "Harrisburg",
        "supervisor_email": "tim@timwis.com"
    },
    "created": "2016-09-29T11:55:01.802Z"
}
```

You would expect the UI's URL to change to `/travel-request/6` and to show the submitted case as if you were viewing it. No actions available, just the read-only submission and its current status/event history.

But if you take the user to `/travel-request/6`, it requests `/api/travel-request/6/`, which throws a `403` because no token was passed.

Technically, we have the data, so we can update the UI without changing the URL. And we're doing that right now. But if you hit refresh, it's gone. And you can't bookmark it.

How should we handle this? We could tell them to check their email, and send them a token that has no `state` or `actions` set on it (read-only token). But part of me feels like we should just respond to the `POST` with that token, so they can be redirected properly. But I'm not sure where that would fit into the response body structure...

**Comment by mjumbewu** [comment]
As of commit 5586c086eeb54fb95db8538082801528a296052b, the `Actor` is stored on the browser session.
- The assignment token is passed down with the serialized `Case` object.
- If you submit a new case and there's no actor currently on the session, a new anonymous actor will be created. An assignment for the initial action is then created for this actor and sent down with the case. This means the URL can be rewritten and the user can always use that assignment token to get back to the case.
- If you submit a new case and an actor _is_ attached to the session (say, because they took an action on some other case), then that actor will be assigned to the initial action. Essentially, stately will remember me while the browser session is valid.

I also added a route (`/api/actor/`) that will return the current session's actor for a _GET_ request, and will "forget" the session's actor (i.e., log out) for a _DELETE_ request. So, we could do something like show who the current actor is and give the user the chance to _Log Out_ if it's not them.

**Comment by timwis** [comment]
Interesting. Playing around with this now and noticing that when someone initiates a travel request, it creates an empty record in the `actor` table:

<img width="346" alt="screen shot 2016-10-02 at 11 37 35" src="https://cloud.githubusercontent.com/assets/761444/19021660/b6ae0ef0-8894-11e6-9ce0-8bdada236475.png">

Is there any reason to do that? Couldn't the `assignment` table just have a `NULL` `actor_id`?

Beyond that, can you elaborate on the problem that the sessions solve / give an example? I'm not following.

**Comment by mjumbewu** [comment]
Yeah, it was primarily so that if you submit multiple cases, even for different workflows, they could be linked to the same person and "claimed" later or something. But that's overthinking for now, and as long as you have the assignment tokens that's still possible. I like the idea of just doing a `NULL` actor instead.
